name: peka_dini
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  http: 0.13.5
  introduction_screen: 3.0.2
  google_fonts: ^3.0.1
  lottie: 2.0.0
  convex_bottom_bar: 3.1.0+1
  flutter: 
    sdk: flutter
  animated_splash_screen: ^1.3.0
  google_nav_bar: ^5.0.6
  font_awesome_flutter: ^10.4.0
  flutter_svg: ^1.1.6
  dropdown_search: ^0.6.1
  flutter_launcher_icons: ^0.12.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/pictures/Logo.png"
  min_sdk_android: 21

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  fonts:
    - family:  MyFlutterApp
      fonts:
       - asset: assets/fonts/MyFlutterApp.ttf
  assets: 
    - assets/lotties/
    - assets/fonts/MyFlutterApp.ttf
    - assets/pictures/
  uses-material-design: true

